name: DP-EasyWarning
version: 1.0.0.4
main: com.licker2689.lew.EasyWarning
authors: [ LICKER2689 ]
api-version: 1.17
depend:
  - LP-Core
commands:
  경고:
    aliases: [lew]
  경고확인:
    aliases: [lewcheck]
