name: DP-EasyWarning
version: 1.0.0.2
main: com.darksoldier1404.dew.EasyWarning
authors: [ DEAD_POOLIO_ ]
api-version: 1.16
depend:
  - DPP-Core
commands:
  경고:
    aliases: [dew]
  경고확인:
    aliases: [dewcheck]
